import type { Category, Download, Settings } from '../types';

// A fixed base time so fixtures are deterministic and dates render sensibly.
// (We don't call Date.now() at module load; the ticker uses live time.)
const T = (offsetMinutes: number): string =>
  new Date(Date.parse('2026-07-11T09:00:00.000Z') + offsetMinutes * 60_000).toISOString();

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: 'general',
    name: 'General',
    folder: 'C:\\Users\\USER\\Downloads',
    extensions: [],
  },
  {
    id: 'compressed',
    name: 'Compressed',
    folder: 'C:\\Users\\USER\\Downloads\\Compressed',
    extensions: ['zip', 'rar', '7z', 'gz', 'tar'],
  },
  {
    id: 'documents',
    name: 'Documents',
    folder: 'C:\\Users\\USER\\Downloads\\Documents',
    extensions: ['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt'],
  },
  {
    id: 'music',
    name: 'Music',
    folder: 'C:\\Users\\USER\\Downloads\\Music',
    extensions: ['mp3', 'flac', 'wav', 'aac', 'm4a'],
  },
  {
    id: 'video',
    name: 'Video',
    folder: 'C:\\Users\\USER\\Downloads\\Video',
    extensions: ['mp4', 'mkv', 'avi', 'mov', 'webm'],
  },
  {
    id: 'programs',
    name: 'Programs',
    folder: 'C:\\Users\\USER\\Downloads\\Programs',
    extensions: ['exe', 'msi', 'dmg', 'deb', 'rpm'],
  },
];

export const DEFAULT_SETTINGS: Settings = {
  downloadDir: 'C:\\Users\\USER\\Downloads',
  maxConcurrent: 4,
  globalSpeedLimitBps: null,
  categories: DEFAULT_CATEGORIES,
  clipboardMonitoring: true,
  notifyOnComplete: true,
  shutdownOnComplete: false,
  schedule: { enabled: false, startHHmm: '01:00', stopHHmm: '08:00' },
};

const MB = 1024 * 1024;
const GB = 1024 * MB;

function segments(count: number, from: number, to: number, done: number[]): Download['segments'] {
  const span = Math.floor((to - from) / count);
  return Array.from({ length: count }, (_, i) => ({
    index: i,
    from: from + i * span,
    to: i === count - 1 ? to : from + (i + 1) * span - 1,
    done: done[i] ?? 0,
  }));
}

export function makeFixtures(): Download[] {
  return [
    // --- active, multi-segment HTTP download -------------------------------
    {
      id: 'd-active-1',
      url: 'https://releases.example.com/app/Setup-14.2.1-x64.exe',
      filename: 'Setup-14.2.1-x64.exe',
      destinationPath: 'C:\\Users\\USER\\Downloads\\Programs',
      category: 'programs',
      kind: 'http',
      sizeBytes: 512 * MB,
      downloadedBytes: Math.floor(512 * MB * 0.42),
      progressPct: 42,
      speedBps: 6.4 * MB,
      etaSeconds: 47,
      supportsResume: true,
      state: 'active',
      dateAdded: T(-12),
      segments: segments(8, 0, 512 * MB, [
        Math.floor(64 * MB * 0.9),
        Math.floor(64 * MB * 0.7),
        Math.floor(64 * MB * 0.55),
        Math.floor(64 * MB * 0.4),
        Math.floor(64 * MB * 0.3),
        Math.floor(64 * MB * 0.2),
        Math.floor(64 * MB * 0.1),
        Math.floor(64 * MB * 0.05),
      ]),
    },
    // --- active HTTP, size unknown (HEAD not done) -------------------------
    {
      id: 'd-active-unknown',
      url: 'https://cdn.example.net/stream/dataset.bin',
      filename: 'dataset.bin',
      destinationPath: 'C:\\Users\\USER\\Downloads',
      category: 'general',
      kind: 'http',
      sizeBytes: null,
      downloadedBytes: 88 * MB,
      progressPct: 0,
      speedBps: 2.1 * MB,
      etaSeconds: null,
      supportsResume: false,
      state: 'active',
      dateAdded: T(-6),
    },
    // --- connecting --------------------------------------------------------
    {
      id: 'd-connecting-1',
      url: 'https://mirror.example.org/iso/ubuntu-24.04-desktop-amd64.iso',
      filename: 'ubuntu-24.04-desktop-amd64.iso',
      destinationPath: 'C:\\Users\\USER\\Downloads',
      category: 'general',
      kind: 'http',
      sizeBytes: 5.9 * GB,
      downloadedBytes: 0,
      progressPct: 0,
      speedBps: 0,
      etaSeconds: null,
      supportsResume: true,
      state: 'connecting',
      dateAdded: T(-2),
    },
    // --- queued ------------------------------------------------------------
    {
      id: 'd-queued-1',
      url: 'https://files.example.com/archive/backup-2026-07.zip',
      filename: 'backup-2026-07.zip',
      destinationPath: 'C:\\Users\\USER\\Downloads\\Compressed',
      category: 'compressed',
      kind: 'http',
      sizeBytes: 1.8 * GB,
      downloadedBytes: 0,
      progressPct: 0,
      speedBps: 0,
      etaSeconds: null,
      supportsResume: true,
      state: 'queued',
      dateAdded: T(-1),
    },
    // --- paused, resumable -------------------------------------------------
    {
      id: 'd-paused-1',
      url: 'https://media.example.com/podcasts/episode-238.mp3',
      filename: 'episode-238.mp3',
      destinationPath: 'C:\\Users\\USER\\Downloads\\Music',
      category: 'music',
      kind: 'http',
      sizeBytes: 92 * MB,
      downloadedBytes: Math.floor(92 * MB * 0.63),
      progressPct: 63,
      speedBps: 0,
      etaSeconds: null,
      supportsResume: true,
      state: 'paused',
      dateAdded: T(-40),
      segments: segments(4, 0, 92 * MB, [
        Math.floor(23 * MB * 0.9),
        Math.floor(23 * MB * 0.7),
        Math.floor(23 * MB * 0.5),
        Math.floor(23 * MB * 0.42),
      ]),
    },
    // --- paused, NOT resumable (no range support) --------------------------
    {
      id: 'd-paused-noresume',
      url: 'https://legacy.example.com/report.pdf',
      filename: 'annual-report.pdf',
      destinationPath: 'C:\\Users\\USER\\Downloads\\Documents',
      category: 'documents',
      kind: 'http',
      sizeBytes: 14 * MB,
      downloadedBytes: Math.floor(14 * MB * 0.31),
      progressPct: 31,
      speedBps: 0,
      etaSeconds: null,
      supportsResume: false,
      state: 'paused',
      dateAdded: T(-55),
    },
    // --- video with formats ------------------------------------------------
    {
      id: 'd-video-1',
      url: 'https://videos.example.com/watch?v=Kx9d2Lm',
      filename: 'How It Is Made — Full Documentary.mp4',
      destinationPath: 'C:\\Users\\USER\\Downloads\\Video',
      category: 'video',
      kind: 'video',
      sizeBytes: 720 * MB,
      downloadedBytes: Math.floor(720 * MB * 0.18),
      progressPct: 18,
      speedBps: 3.7 * MB,
      etaSeconds: 160,
      supportsResume: true,
      state: 'active',
      dateAdded: T(-8),
      video: {
        title: 'How It Is Made — Full Documentary',
        selectedFormatId: 'v-1080',
        formats: [
          { id: 'v-2160', label: '2160p (4K)', ext: 'mp4', sizeBytes: 3.2 * GB, hasVideo: true, hasAudio: true },
          { id: 'v-1440', label: '1440p (QHD)', ext: 'mp4', sizeBytes: 1.6 * GB, hasVideo: true, hasAudio: true },
          { id: 'v-1080', label: '1080p (Full HD)', ext: 'mp4', sizeBytes: 720 * MB, hasVideo: true, hasAudio: true },
          { id: 'v-720', label: '720p (HD)', ext: 'mp4', sizeBytes: 420 * MB, hasVideo: true, hasAudio: true },
          { id: 'v-480', label: '480p', ext: 'mp4', sizeBytes: 210 * MB, hasVideo: true, hasAudio: true },
          { id: 'v-video-only', label: '1080p (video only)', ext: 'mp4', sizeBytes: 640 * MB, hasVideo: true, hasAudio: false },
          { id: 'a-audio-only', label: 'Audio only (m4a)', ext: 'm4a', sizeBytes: 62 * MB, hasVideo: false, hasAudio: true },
        ],
      },
    },
    // --- torrent -----------------------------------------------------------
    {
      id: 'd-torrent-1',
      url: 'magnet:?xt=urn:btih:8f3a2b1c9d4e5f6a7b8c9d0e1f2a3b4c5d6e7f80&dn=OpenDataset',
      filename: 'OpenDataset-2026.tar',
      destinationPath: 'C:\\Users\\USER\\Downloads',
      category: 'general',
      kind: 'torrent',
      sizeBytes: 4.4 * GB,
      downloadedBytes: Math.floor(4.4 * GB * 0.76),
      progressPct: 76,
      speedBps: 11.2 * MB,
      etaSeconds: 92,
      supportsResume: true,
      state: 'active',
      dateAdded: T(-30),
      torrent: { peers: 48, seeders: 21, ratio: 1.34 },
    },
    // --- completed ---------------------------------------------------------
    {
      id: 'd-completed-1',
      url: 'https://releases.example.com/tool/tool-3.9.0-win.zip',
      filename: 'tool-3.9.0-win.zip',
      destinationPath: 'C:\\Users\\USER\\Downloads\\Compressed',
      category: 'compressed',
      kind: 'http',
      sizeBytes: 128 * MB,
      downloadedBytes: 128 * MB,
      progressPct: 100,
      speedBps: 0,
      etaSeconds: 0,
      supportsResume: true,
      state: 'completed',
      dateAdded: T(-220),
      dateCompleted: T(-210),
    },
    {
      id: 'd-completed-2',
      url: 'https://media.example.com/wallpapers/pack-4k.zip',
      filename: '4k-wallpaper-pack.zip',
      destinationPath: 'C:\\Users\\USER\\Downloads',
      category: 'general',
      kind: 'http',
      sizeBytes: 96 * MB,
      downloadedBytes: 96 * MB,
      progressPct: 100,
      speedBps: 0,
      etaSeconds: 0,
      supportsResume: true,
      state: 'completed',
      dateAdded: T(-1440),
      dateCompleted: T(-1430),
    },
    // --- error -------------------------------------------------------------
    {
      id: 'd-error-1',
      url: 'https://broken.example.com/files/huge-video.mkv',
      filename: 'huge-video.mkv',
      destinationPath: 'C:\\Users\\USER\\Downloads\\Video',
      category: 'video',
      kind: 'http',
      sizeBytes: 2.3 * GB,
      downloadedBytes: Math.floor(2.3 * GB * 0.54),
      progressPct: 54,
      speedBps: 0,
      etaSeconds: null,
      supportsResume: true,
      state: 'error',
      error: 'Connection reset by peer (HTTP 503)',
      dateAdded: T(-90),
    },
    // --- canceled ----------------------------------------------------------
    {
      id: 'd-canceled-1',
      url: 'https://files.example.com/misc/old-installer.msi',
      filename: 'old-installer.msi',
      destinationPath: 'C:\\Users\\USER\\Downloads\\Programs',
      category: 'programs',
      kind: 'http',
      sizeBytes: 240 * MB,
      downloadedBytes: Math.floor(240 * MB * 0.12),
      progressPct: 12,
      speedBps: 0,
      etaSeconds: null,
      supportsResume: true,
      state: 'canceled',
      dateAdded: T(-160),
    },
  ];
}
