// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['main']['App']['Add'](arg1);
}

export function AddTorrent(arg1) {
  return window['go']['main']['App']['AddTorrent'](arg1);
}

export function Cancel(arg1) {
  return window['go']['main']['App']['Cancel'](arg1);
}

export function CopyUrl(arg1) {
  return window['go']['main']['App']['CopyUrl'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListDownloads() {
  return window['go']['main']['App']['ListDownloads']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function Pause(arg1) {
  return window['go']['main']['App']['Pause'](arg1);
}

export function PauseAll() {
  return window['go']['main']['App']['PauseAll']();
}

export function PickFolder(arg1) {
  return window['go']['main']['App']['PickFolder'](arg1);
}

export function ProbeVideo(arg1) {
  return window['go']['main']['App']['ProbeVideo'](arg1);
}

export function Remove(arg1, arg2) {
  return window['go']['main']['App']['Remove'](arg1, arg2);
}

export function Reorder(arg1) {
  return window['go']['main']['App']['Reorder'](arg1);
}

export function Resume(arg1) {
  return window['go']['main']['App']['Resume'](arg1);
}

export function ResumeAll() {
  return window['go']['main']['App']['ResumeAll']();
}

export function Retry(arg1) {
  return window['go']['main']['App']['Retry'](arg1);
}

export function SelectVideoFormat(arg1, arg2) {
  return window['go']['main']['App']['SelectVideoFormat'](arg1, arg2);
}

export function SetDownloadSpeedLimit(arg1, arg2) {
  return window['go']['main']['App']['SetDownloadSpeedLimit'](arg1, arg2);
}

export function SetGlobalSpeedLimit(arg1) {
  return window['go']['main']['App']['SetGlobalSpeedLimit'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
