// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['main']['App']['Add'](arg1);
}

export function AddTorrent(arg1) {
  return window['go']['main']['App']['AddTorrent'](arg1);
}

export function AddTorrentFile() {
  return window['go']['main']['App']['AddTorrentFile']();
}

export function BeginBrowserSetup(arg1) {
  return window['go']['main']['App']['BeginBrowserSetup'](arg1);
}

export function Cancel(arg1) {
  return window['go']['main']['App']['Cancel'](arg1);
}

export function CompleteBrowserOnboarding() {
  return window['go']['main']['App']['CompleteBrowserOnboarding']();
}

export function CopyUrl(arg1) {
  return window['go']['main']['App']['CopyUrl'](arg1);
}

export function ExportDiagnostics() {
  return window['go']['main']['App']['ExportDiagnostics']();
}

export function GetBrowserIntegration() {
  return window['go']['main']['App']['GetBrowserIntegration']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSystemAccent() {
  return window['go']['main']['App']['GetSystemAccent']();
}

export function GetVideoToolsHealth() {
  return window['go']['main']['App']['GetVideoToolsHealth']();
}

export function InstallVideoTools() {
  return window['go']['main']['App']['InstallVideoTools']();
}

export function ListDownloads() {
  return window['go']['main']['App']['ListDownloads']();
}

export function MoveToQueue(arg1, arg2) {
  return window['go']['main']['App']['MoveToQueue'](arg1, arg2);
}

export function NeedsBrowserOnboarding() {
  return window['go']['main']['App']['NeedsBrowserOnboarding']();
}

export function OpenBrowserExtensions(arg1) {
  return window['go']['main']['App']['OpenBrowserExtensions'](arg1);
}

export function OpenExtensionFolder() {
  return window['go']['main']['App']['OpenExtensionFolder']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function Pause(arg1) {
  return window['go']['main']['App']['Pause'](arg1);
}

export function PauseAll() {
  return window['go']['main']['App']['PauseAll']();
}

export function PickFolder(arg1) {
  return window['go']['main']['App']['PickFolder'](arg1);
}

export function ProbeVideo(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProbeVideo'](arg1, arg2, arg3);
}

export function Remove(arg1, arg2) {
  return window['go']['main']['App']['Remove'](arg1, arg2);
}

export function Reorder(arg1) {
  return window['go']['main']['App']['Reorder'](arg1);
}

export function ResetSettings() {
  return window['go']['main']['App']['ResetSettings']();
}

export function Resume(arg1) {
  return window['go']['main']['App']['Resume'](arg1);
}

export function ResumeAll() {
  return window['go']['main']['App']['ResumeAll']();
}

export function Retry(arg1) {
  return window['go']['main']['App']['Retry'](arg1);
}

export function RollbackVideoTools() {
  return window['go']['main']['App']['RollbackVideoTools']();
}

export function SelectVideoFormat(arg1, arg2) {
  return window['go']['main']['App']['SelectVideoFormat'](arg1, arg2);
}

export function SetDownloadSpeedLimit(arg1, arg2) {
  return window['go']['main']['App']['SetDownloadSpeedLimit'](arg1, arg2);
}

export function SetGlobalSpeedLimit(arg1) {
  return window['go']['main']['App']['SetGlobalSpeedLimit'](arg1);
}

export function SetQueueRunning(arg1, arg2) {
  return window['go']['main']['App']['SetQueueRunning'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateVideoTools() {
  return window['go']['main']['App']['UpdateVideoTools']();
}

export function VideoToolsReady() {
  return window['go']['main']['App']['VideoToolsReady']();
}
