// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {main} from '../models';

export function Add(arg1:backend.AddRequest):Promise<backend.Download>;

export function AddTorrent(arg1:string):Promise<backend.Download>;

export function AddTorrentFile():Promise<backend.Download>;

export function BeginBrowserSetup(arg1:string):Promise<void>;

export function Cancel(arg1:string):Promise<void>;

export function CompleteBrowserOnboarding():Promise<void>;

export function CopyUrl(arg1:string):Promise<void>;

export function ExportDiagnostics():Promise<string>;

export function GetBrowserIntegration():Promise<main.BrowserIntegrationInfo>;

export function GetSettings():Promise<backend.Settings>;

export function GetSystemAccent():Promise<main.AccentPalette>;

export function GetVideoToolsHealth():Promise<backend.VideoToolsHealth>;

export function InstallVideoTools():Promise<void>;

export function ListDownloads():Promise<Array<backend.Download>>;

export function MoveToQueue(arg1:Array<string>,arg2:string):Promise<void>;

export function NeedsBrowserOnboarding():Promise<boolean>;

export function OpenBrowserExtensions(arg1:string):Promise<void>;

export function OpenExtensionFolder():Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function Pause(arg1:string):Promise<void>;

export function PauseAll():Promise<void>;

export function PickFolder(arg1:string):Promise<string>;

export function ProbeURL(arg1:string,arg2:string):Promise<backend.UrlProbe>;

export function ProbeVideo(arg1:string,arg2:string,arg3:string):Promise<backend.VideoInfo>;

export function Remove(arg1:string,arg2:boolean):Promise<void>;

export function Reorder(arg1:Array<string>):Promise<void>;

export function ResetSettings():Promise<backend.Settings>;

export function Resume(arg1:string):Promise<void>;

export function ResumeAll():Promise<void>;

export function Retry(arg1:string):Promise<void>;

export function RollbackVideoTools():Promise<void>;

export function SelectVideoFormat(arg1:string,arg2:string):Promise<void>;

export function SetDownloadSpeedLimit(arg1:string,arg2:any):Promise<void>;

export function SetGlobalSpeedLimit(arg1:any):Promise<void>;

export function SetQueueRunning(arg1:string,arg2:boolean):Promise<void>;

export function UpdateSettings(arg1:backend.Settings):Promise<void>;

export function UpdateVideoTools():Promise<void>;

export function VideoToolsReady():Promise<boolean>;
